### ISSUE TITLE
[RFE] Provides selection callback mechanism

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/libsolv#107]
Partly due to what's been experienced in Fedora (see #66) and partly due to my work to introduce DNF into Mageia (see #106 for some patches I've submitted in regards to these efforts) and my efforts to ensure DNF is a strong functional replacement, I've encountered cases where it would be nice if it were possible for the user to be able to select what would satisfy a Requires, when multiple "equally useful" options are available.

I filed a [request for the feature in DNF](https://bugzilla.redhat.com/show_bug.cgi?id=1266761), however it was closed because it isn't possible without a mechanism in libsolv to do it.

It would be nice if this part of the libsolv README became true:
> [...] allows to provide the user with suggestions on how to deal with unsolvable problems.

Please consider implementing it.

**Comment by mlschroe** [comment]
The libsolv philosophy is a bit different: we don't support a callback for ambiguities when they are encountered, as with backtracking it's possible that we have to take a different branch anyway.

Instead, libsolv offers methods to query for the encountered ambiguities after the solving, so that the user can be presented with a list of choices and then select different packages. DNF doesn't make use of this feature yet, though.
