### ISSUE TITLE
obsoletes policy is too strict

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/libsolv#143]
```
repo system 0 testtags <inline>
#>=Pkg: hawkey 0.6.3 1 x86_64
#>=Pkg: python3-hawkey 0.6.3 1 x86_64
#>=Req: hawkey = 0.6.3-1
repo cmdline 0 testtags <inline>
#>=Pkg: libdnf 0.7.0 1 x86_64
#>=Obs: hawkey < 0.7.0
system x86_64 rpm system
poolflags implicitobsoleteusescolors
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes
job install name libdnf
result transaction,problems <inline>
install libdnf-0.7.0-1.x86_64@cmdline
```

```
Results differ:
-install libdnf-0.7.0-1.x86_64@cmdline
+problem 2daa8933 info package python3-hawkey-0.6.3-1.x86_64 requires hawkey = 0.6.3-1, but none of the providers can be installed
+problem 2daa8933 solution 3a6296af deljob install name libdnf
+problem 2daa8933 solution cc7d4017 erase python3-hawkey-0.6.3-1.x86_64@system
```

I don't see any problems why `libdnf` can't be installed even it has obsoletes. I think obsoletes should be handled only for update.

**Comment by Conan-Kudo** [comment]
No, you're using it wrong. You should not obsolete hawkey itself, only python2-hawkey and python3-hawkey.

**Comment by ignatenkobrain** [comment]
> No, you're using it wrong. You should not obsolete hawkey itself, only
python2-hawkey and python3-hawkey.
This is intended.

**Comment by Conan-Kudo** [comment]
@ignatenkobrain Then libsolv is working as intended. If you intend to obsolete hawkey, then it should do exactly that.

Obsoleting hawkey is probably the wrong choice anyway, since libhif/libdnf is *not* an equivalent library and they can indeed happily coexist. [tdnf](https://github.com/vmware/tdnf) uses the C library, and there's literally no reason to break that.

Just don't do it.

**Comment by mlschroe** [comment]
libsolv does what rpm does. Don't complain here, go to rpm upstream. ;)
