### ISSUE TITLE
obsoletes doesn't get installed

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/libsolv#146]
```
repo system 0 testtags <inline>
#>=Pkg: foo 1 1 noarch
repo available 0 testtags <inline>
#>=Pkg: foo 2 1 noarch
#>=Pkg: foo-split 2 1 noarch
#>=Obs: foo < 2
#>=Req: foo >= 2

system x86_64 rpm system

poolflags implicitobsoleteusescolors
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes
job update all packages
result transaction,problems <inline>
#>upgrade foo-1-1.noarch@system foo-2-1.noarch@available
#>install foo-split-2-1.noarch@available
```

**Comment by mlschroe** [comment]
This is actually by design. It works if you also add the Obsoletes to the main package.

**Comment by ignatenkobrain** [comment]
@mlschroe but it's not correct according our non-official guidelines. And I think ti's logical. We have some example for that from past:
Having `NetworkManager`, we created some subpackages like `-wifi`, `-openvpn` and we want users to install it if they upgrading their system, otherwise they will loose functionality (I broke my system like this because I didn't got `-wifi` subpkg installed)

**Comment by mlschroe** [comment]
But I need a way to distinguish alternatives from obsolete groups. Say you don't have that "foo" package in the repo. Then it's just a rename, "foo-split" contains "Obsoletes: foo < 2". But if the user adds some private repo that contains "foo" in a higher version, it will suddenly get dragged in.

You could say that obsolete groups must be from the same repo, but I bet there are use cases for splitting a repo.

**Comment by mlschroe** [comment]
What I'm trying to solve is the "user has multiple repos from different vendors" case. Say there's a simple rename in fedora, "foo" gets renamed to "foo-new". So "foo-new" gets a provides/obsoletes combination. Then the user adds another repo (e.g. copr) which contains a unsplit "foo" package. I don't want rpm to install both "foo" and "foo-new" in that case.

I could check that both packages come from the same repo, but I don't really like to use the repo for this. Maybe someone decides to split the repo. Or create a master repo from different other repos.

I could check if the buildtime and the vendor is the same. This would work for subpacks split, but it's also kind of hacky.

**Comment by kkofler** [comment]
The key there is the Requires. If `foo-split` has only:
```
Obsoletes: foo < 2
```
then `foo-split` should be preferred over a newer `foo` (i.e., `foo` should get removed). If `foo-split` actually has:
```
Obsoletes: foo < 2
Requires: foo >= 2
```
then **both** the updated `foo` and `foo-split` need to be installed.

**Comment by ignatenkobrain** [comment]
@kkofler yep.

@mlschroe any news?

**Comment by mschwendt** [comment]
One downstream bug report for #191 is http://bugzilla.redhat.com/1439690
It includes a test-case with existing packages and updates.

**Comment by ignatenkobrain** [comment]
So seems that original use-case now works fine, it just upgrades foo to 2-1, and doesn't install Obsolete. Adding obsoletes into main package makes libsolv to install -split too.

**Comment by kkofler** [comment]
> So seems that original use-case now works fine, it just upgrades foo to 2-1, and doesn't install Obsolete.

No, that is exactly what should **not** happen and what this bug is complaining about. `Obsoletes` should be preferred over a regular upgrade.

**Comment by kkofler** [comment]
This issue is once again breaking things (including, ironically, dnf itself) in the real world in Fedora:
https://bugzilla.redhat.com/show_bug.cgi?id=1669950

**Please** reopen this issue and do something about it!

**Comment by kkofler** [comment]
Let me try to explain the expected behavior, i.e., the one to which the Fedora packaging guidelines were written (and the one which was implemented by the legacy Yum):

1. Installed:
* foo: Version = 1
Available:
* foo: Version = 2
* foo1: Obsoletes: foo < 2
Expected behavior: ignores foo version 2, installs foo1 instead, because Obsoletes should **always** be preferred to a regular upgrade.

2. Installed:
* foo: Version = 1
Available:
* foo: Version = 2, Obsoletes: foo < 2
* foo1: Obsoletes: foo < 2
Expected behavior: installs both foo and foo1 because **both** have an Obsoletes on the same installed package.

3. Installed:
* foo: Version = 1
Available:
* foo: Version = 2
* foo1: Obsoletes: foo < 2, Requires: foo
Expected behavior: installs both foo and foo1 because first foo1 (but not foo) should be dragged in as in case 1, and then foo should get dragged in (after all) by the Requires in foo1.

Case 1 is the one that is not working as expected, causing the failure in https://bugzilla.redhat.com/show_bug.cgi?id=1669950 which breaks dnf, fedora-easy-karma, etc.

**Comment by mlschroe** [comment]
Speaking about bug 1669950, that's a dependency problem that needs to be fixed. A fresh install (i.e. not an update) might also get libmodulemd = 2 instead of libmodulemd1, leading to a broken system.
