### ISSUE TITLE
don't bring weak deps on update if they do not exist

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/libsolv#168]
```
repo system 0 testtags <inline>
#>=Pkg: dnf 1 1 noarch
#>=Rec: bash-completion
repo available 0 testtags <inline>
#>=Pkg: dnf 1 2 noarch
#>=Rec: bash-completion
#>=Pkg: bash-completion 1 1 noarch

system x86_64 rpm system

poolflags implicitobsoleteusescolors
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes
job update all packages
result transaction,problems <inline>
#>upgrade dnf-1-1.noarch@system dnf-1-2.noarch@available
```

```
Results differ:
+install bash-completion-1-1.noarch@available
```

I'm pretty sure we have some bugreports about this, but anyway it's annoying.

**Comment by mlschroe** [comment]
Ah, it's a feature. Anyway, it's pretty impossible to fix.

The problem is that there is no information why bash-completion is not installed. Is it because it was not available in the repos before? Or it was not installable because some other installed packages conflicted with it? Or some dependency could not be met at the time? Or the user installed dnf with weak deps disabled? Or it was installed and got deinstalled?

So we simply don't know what the reason is. Just ignoring the Recommends is as wrong as installing it. Add the package to your exclude list if you don't want to have it installed. (Or disfavor list at some point in dnf's future...)

**Comment by kkofler** [comment]
Please reopen this issue. When I update `foo-1` to `foo-2`, that should only install `Recommends` that are **new** in `foo-2` (i.e., that are contained in the set difference `Recommends(foo-2)\Recommends(foo-1)`). If the `Recommends` was already present in `foo-1`, but the package was not installed on the system, it should be assumed that that was for a reason.

This is different from installing `foo-2` on a system with no `foo` installed, where of course you want to default to dragging in all its `Recommends`.

This issue is making `Recommends` essentially useless, because packages are upgraded quite often around here (on Fedora), and so weak dependencies that the user opted out of keep getting dragged in again and again, which is extremely annoying.

**Comment by Conan-Kudo** [comment]
And technically, DNF _does_ have the information to know why something wasn't installed. We can record install/erase reasons. @ignatenkobrain might know if we also record why something wasn't installed in a proposed transaction when it could have been.

**Comment by mlschroe** [comment]
But how did you 'opt out of' getting a package? Isn't that what needs to be recorded instead of a change in libsolv? My point is that a recommended package that couldn't be installed because of some dependency issue *should* be installed on the update.

**Comment by kkofler** [comment]
Why? The previous state was that you had `foo-1` without its recommended dependency `bar`, so after updating to a newer `foo-2`, the most logical state to move to is to have `foo-2` without its recommended dependency `bar`. The fact that you have `foo` without `bar` did not change just because `foo-1` was upgraded to `foo-2`. Otherwise, to be consistent you would have to suggest reinstalling `bar` on each and every operation, no matter whether it involves `foo`, which would be even more annoying in practice.

And there are 2 straightforward ways the user can have opted out: either just `dnf remove bar` with `foo` already installed, or `dnf --exclude=bar install foo`.

I think the case that you mentioned, where there was some dependency issue with `bar` when `foo-1` was installed which is no longer there when upgrading `foo-1` to `foo-2`, is very rare and a lot less likely than that the user deliberately opted out of `bar` one way or the other. And I also doubt installing `bar` at that point is really what the user wants even in that case, as they had `foo` without `bar` already for some time at that point without doing anything about it, possibly even months.

**Comment by t8m** [comment]
Why should some random upate of foo try to "fix" things? There probably should be some flag that would allow me to install such missing weak dependencies but normally on updates I would expect only newly appearing weak deps to be installed.
