### ISSUE TITLE
Publish pip-installable Python bindings

### ISSUE THREAD

**Issue by ncoghlan** [openSUSE/libsolv#228]
This is less an issue-to-be-resolved and more an FYI regarding the previously unclaimed `solv` name on PyPI: I've started a pypi-solv project at https://github.com/ncoghlan/pypi-solv with the aim of producing a pip-installable sdist and a manylinux1 wheel file for libsolv's Python bindings.

Right now, that's just a placeholder module that does nothing more than emit a runtime warning when imported: https://pypi.org/project/solv/0.0.1/

Longer term, I'm aiming to make it default to providing a standalone statically linked version of the extension module: https://github.com/ncoghlan/pypi-solv/issues/1

**Comment by ignatenkobrain** [comment]
Seems that pypi-solv repo is archived now and I don't think there is much benefit of publishing bindings to PyPI from upstream project. So closing.

**Comment by crazyscientist** [comment]
Actually, I kind of find it weird, if projects decide against publishing their Python packages via PyPi. Python's dependency management is quite comfortable, but every time a package is not available one has to tell other people: "Please don't forget to also install that".

**Comment by dralley** [comment]
@ncoghlan @ignatenkobrain 

I spent a few hours getting libsolv packageable as a Python package, as I have with createrepo_c and libcomps, because it's useful to the Pulp project to be able to use Python packages instead of RPMs (CI/CD, upstream source installations, etc.)

If you would be receptive to merging that work, I can clean it up and make a PR.  We'll probably use it even if the packages don't end up on PyPi.

re: the description of https://pypi.org/project/solv/, I am using scikit-build (cmake integration for setuptools), which predates pep517 and supporting it is still an open issue.  Not sure how much that matters.

**Comment by dralley** [comment]
I now have something that seems to be functional, though I haven't tested it thoroughly and the patch is obviously more messy than it needs to be.  I just commented out everything that needed to be disabled (docs, headers, tests, etc.)

![Screenshot from 2020-02-12 23-39-48](https://user-images.githubusercontent.com/2751996/74402093-42b77d80-4df1-11ea-9c70-c7bc480363d4.png)

https://github.com/openSUSE/libsolv/compare/master...dralley:python-package

**Comment by dralley** [comment]
@ncoghlan I got a CI set up to automatically build platform-independent wheels: https://github.com/dralley/libsolv/runs/447432218?check_suite_focus=true#step:7:228

Are you still interested in this package?  If not, and if libsolv upstream is also not interested, would you consider giving access to https://pypi.org/user/pulp/?

**Comment by dralley** [comment]
@ignatenkobrain @mlschroe 

I've released the first libsolv packages to PyPI: https://pypi.org/project/solv/#history

If it's something the upstream project might now be interested in, I can clean up the patch and work to have it upstreamed.  Otherwise, we will just maintain it ourselves.
