### ISSUE TITLE
install pulls in an i686 package with forcebest 

### ISSUE THREAD

**Issue by lukash** [openSUSE/libsolv#383]
Hello, I've put together a minimal test case for a problem we're having with installing a package with `forcebest`:
https://github.com/lukash/libsolv/tree/forcebest-arch

There are two test cases, [`update.t`](https://github.com/lukash/libsolv/blob/forcebest-arch/test/testcases/forcebest-arch/update.t) correctly updates the package including its dependencies, but [`install.t`](https://github.com/lukash/libsolv/blob/forcebest-arch/test/testcases/forcebest-arch/install.t) pulls in the `i686` version of the package to satisfy installed dependencies instead of updating them, as seen in [`install.result`](https://github.com/lukash/libsolv/blob/forcebest-arch/test/testcases/forcebest-arch/install.result) (which shows what is erroneously happening, not the expected result).

I'm not sure if I should report this in a better way (the test case will disappear once i delete the branch and won't be here for future reference), but the test case is a bit long and spread over multiple files, so a branch seemed like the best way to share it.

**Comment by mlschroe** [comment]
It's because of python3-libstoragemgmt-1.0-1 requires libstoragemgmt = 1.0-1 (but you probably already knew that). It's the job of the "choice rules" to make the solver update packages instead of installing new ones, but they do not seem to work for different architectures.

It happens because the solver does the following steps in order:
- resolve job rules
- resolve installed packages (i.e. keep or update)
- resolve package dependencies

If the third step needs a dependency that is not fulfilled by an installed package, it looks at new packages (in your case the i686 packages). It will no longer update installed packages - it needs to backtrack to do this. Here's where choice rules come into play: they forbid the installation of new packages. They are marked as weak, so they can be broken when there is no other way to fulfill the request.

I'll try to tweak the choice rule generation so that it also works for packages with different architecture.

**Comment by mlschroe** [comment]
(You can also work around this by removing the  SOLVER_SETARCH flag from the job. See also issue #149.)

**Comment by mlschroe** [comment]
(Why is there a SOLVER_SETARCH anyway when the arch is not fixed?)

**Comment by lukash** [comment]
No idea, I may look into it but I don't know the history, maybe @j-mracek could know more?

**Comment by j-mracek** [comment]
I am not 100% because I played with it about 3 years ago. I believe that we use SOLVER_SETARCH because when we put libstoragemgmt-1.0-1.i686@repo1 in job (oneof) on x86_64 we don't want that it will be handled like libstoragemgmt-1.0-1 without an arch and it will result in installation libstoragemgmt-1.0-1.x86_64@repo instead.

**Comment by lukash** [comment]
@mlschroe any update here? https://github.com/openSUSE/libsolv/issues/387#issuecomment-650217594 indicates you've made some effort to solve this?

**Comment by mlschroe** [comment]
I now have a fix, but it breaks two of the old libzypp testcases. So it needs a bit more tweaking. It should be ready next week.

**Comment by lukash** [comment]
Great news, @mlschroe, thank you.

**Comment by mlschroe** [comment]
This tuned out to be a lot harder than expected. Fixed in commit 894382f0c4ddf6d34b264544c3523a9094ec2a09

**Comment by lukash** [comment]
Thanks, @mlschroe. Works for my test case, I'll create a test in dnf CI as well. I was wondering whether you'd like to adopt the test case for libsolv test suite as well? I see you've added a test for your change yourself, but it seems unrelated to arches. The thing here is there are a ton of corner cases and if someone asks you what they are, you won't come up with many. Since we have an interesting one here, seems worth it to add it to the test suite. (maybe it could be simplified a bit more...)

**Comment by mlschroe** [comment]
I don't think we need another testcase, because the problem was really unrelated to the architecture handling.

**Comment by lukash** [comment]
TBH I think the test case is useful and I feel bad about throwing it away :slightly_frowning_face:
