### ISSUE TITLE
How to get additional information about resolved transaction?

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#450]
This is not an issue but kind request for the help.

DNF is not much informative about why packages were included in transaction created from result of solver_solve(). So far we only report that package is installed as user installed, dep or weak dep. In general we would like to provide additional information like why package was included (which package required it) and also we would like to be able to generate a dependency tree for the transaction. Probably it will be nice to know which dependency is required by required package and which is required by package included to satisfy weak dep. I will be very grateful for any help, answer or information about future plans that will help us.

1. Is there any way how to easily get information about relations of packages in transaction from libsolv?

In theory we can use reverse engineering (query dependencies) for simple installation operation, but in case when installing and removing packages to for example resolve conflict it is impossible to do it correctly (without solver help).

2. Is there a better way how to identify jobs marked with SOLVER_WEAK which were skipped?
At the present time we try to guess it by removal SOLVER_WEAK from all jobs and resolve the transactions again.

3. Is there a better way how to identify that transaction did not use the best candidate for requested jobs?
At the present time we try to guess it by adding SOLVER_FORCEBEST to all jobs and then we resolve it again.

4. Is there any way how to identify packages in transaction that are not the best candidates and installed as dependency?
We do not know how to identify it or how to enforce solver to use only the best candidates like here:
```
repo @System 0 testtags <inline>

repo updates 0 testtags <inline>
#>=Pkg: test-package-alpha 1.0 1 x86_64
#>=Prv: test-package-alpha = 1.0-1
#>=Pkg: test-package-alpha 2.0 1 x86_64
#>=Prv: test-package-alpha = 1.0-1
#>=Req: redhat-storage-logos
#>=Pkg: test 1.0 2 x86_64
#>=Prv: test = 1.0-2
#>=Req: test-package-alpha

system x86_64 rpm @System
poolflags implicitobsoleteusescolors
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes
job install oneof test-1.0-2.x86_64@updates [forcebest,targeted,setevr,setarch]
result transaction,problems <inline>
#>install test-1.0-2.x86_64@updates
#>install test-package-alpha-1.0-1.x86_64@updates
```

**Comment by mlschroe** [comment]
Please have a look at the new `solver_get_decisionlist` function and the implementation for the new `-W` option in the testsolv tool.

**Comment by j-mracek** [comment]
Thank you very much for the suggestion

**Comment by j-mracek** [comment]
@mlschroe I tried `testsolv -W  test-package-alpha-1.0-1.x86_64 testsolv.t` and it provided interesting information.
 `testsolv -W  test-package-alpha testsolv.t` showed
```conflicted test-package-alpha-2.0-1.x86_64@updates because
  nothing provides redhat-storage-logos needed by test-package-alpha-2.0-1.x86_64
```
I believe that it will help us with better information about transaction, but I have to play with it more.

**Comment by j-mracek** [comment]
I started with investigation how to use `solver_get_decisionlist`. Analyzing of `void showwhy(Solver *solv, const char *showwhypkgstr)` helped me to understand how it works. The results are returned on Queue and each element consists if 3 integers (`v`, `reason`, `info`).  And here it gets quite difficult. We would like to use the information as structure to present users relevant information and to allow to format translated text output. But it requires to understand what each meaning each number have.

In past we resolved such a case for solver errors by re-implementation of `solver_problemruleinfo2str(solv, type, source, target, dep)` with fallback to `libsolv` method when new value appeared. But this kind of construct is fragile. Anytime when new thing is implemented on libsolv side we have a problem to identify it. `solver_get_decisionlist` does not have convertor to the string therefore we have very limited possibilities how to decode the logic.

**Comment by AntoinePrv** [comment]
Hi @j-mracek ,

We've been working around new error messages for Mamba as well. We use a function like this one to get all problems form libsolv, parse them into a dependency graph (of the conflicts), and then do a DFS to create the message.
https://github.com/mamba-org/mamba/blob/1f3552271264f77e16f80c7c7f14cd7595b2e75b/libmamba/src/core/solver.cpp#L580

This is experimental, but you can read more about it in our blog post:
https://medium.com/@AntoineProuvost/managing-conflicts-with-mamba-6a5fa10ed6a

**Comment by j-mracek** [comment]
We also have such a methods in Libdnf and libdnf5 - https://github.com/rpm-software-management/dnf5/blob/main/include/libdnf/base/solver_problems.hpp, https://github.com/rpm-software-management/dnf5/blob/main/include/libdnf/base/solver_problems.hpp, plus other code. We even de-duplicate output strings to improve user experience. Anyway Mamba formatting looks interesting.

**Comment by mlschroe** [comment]
Regarding the value of the returned `(v, reason, info)` triplets: the `v` is the decision, it is just the package id. Positive ids means installation (or keeping of installed package), negative means erasing/not installing.

The (reason, info) is just what you get when you call solver_describe_decision() on the decision. The decisionlist algorithm needs the information, so I just also put it in the output instead of throwing it away.

There's a bit of information about the reson values in the libsolv-bindings man page.

For reasons caused by a rule the returned `info` will be the rule id. If you want a textual representation you need to use solver_ruleinfo() on it (or solver_allruleinfos if you want to get all infos). The reason why can be more than one info is because package rules are unified, and multiple package dependencies can result in the same rule. (E.g. if a package requires both librpm and librpmbuild.)

You than can call `solver_problemruleinfo2str()` on the rule info, but I advise against it for two reasons:
- weak rules like recommends or choice rules are not handled, as they can never be part of the problem rule set
- the text output is describing the rule from a problem point of view (i.e. "package XXX requires YYY but none of the providers can be installed"). This is highly confusing if you describe decisions.

Libsolv now has a `solver_ruleinfo2str()` which is more complete and describes the rule in a neutral way.
